language: go

go:
  - "1.15"

script:
  - make
  - tar czvf terraform-provider-harness.tar.gz terraform-provider-harness

deploy:
  provider: releases
  file: terraform-provider-harness.tar.gz
  edge: true # opt in to dpl v2
  on:
    tags: true
